In [ ]:
import pandas as pd
import sqlite3
from sqlalchemy import create_engine, inspect, text, func
from sqlalchemy.orm import Session

In [6]:
# Load the dataset
df = pd.read_csv("data/RealEstate_California.csv")

# Drop rows where hasBadGeocode is 1 (true)
df = df[df["hasBadGeocode"] != 1]

# Drop unneeded columns
df = df.drop(columns=['stateId', 'cityId', 'countyId', 'is_bankOwned', 'description', 'hasBadGeocode', 'is_forAuction', 'country', 
            'currency', 'state', 'id', 'time', 'levels', 'livingAreaValue', 
            'lotAreaUnits', 'buildingArea', 'hasGarage'])

In [7]:
# Convert DataFrame columns to appropriate types
df["id"] = pd.to_numeric(df["Unnamed: 0"], errors="coerce").fillna(0).astype(int)
df.rename(columns={"datePostedString": "date"}, inplace=True)
df["price"] = pd.to_numeric(df["price"], errors="coerce").fillna(0).astype(int)
df["pricePerSquareFoot"] = pd.to_numeric(df["pricePerSquareFoot"], errors="coerce").fillna(0).astype(int)
df["bedrooms"] = pd.to_numeric(df["bedrooms"], errors="coerce").fillna(0).astype(int)
df["bathrooms"] = pd.to_numeric(df["bathrooms"], errors="coerce").fillna(0)
df["streetAddress"] = df["streetAddress"].astype(str)
df["city"] = df["city"].astype(str)
df["zipcode"] = df["zipcode"].astype(str)  # ZIP codes should be text
df["latitude"] = pd.to_numeric(df["latitude"], errors="coerce")
df["longitude"] = pd.to_numeric(df["longitude"], errors="coerce")
df["yearBuilt"] = pd.to_numeric(df["yearBuilt"], errors="coerce").fillna(0).astype(int)
df["livingArea"] = pd.to_numeric(df["livingArea"], errors="coerce").fillna(0).astype(int)
df["parking"] = df["parking"].astype(bool)
df["garageSpaces"] = pd.to_numeric(df["garageSpaces"], errors="coerce").fillna(0).astype(int)
df["pool"] = df["pool"].astype(bool)
df["spa"] = df["spa"].astype(bool)
df["isNewConstruction"] = df["isNewConstruction"].astype(bool)
df["hasPetsAllowed"] = df["hasPetsAllowed"].astype(bool)
df["homeType"] = df["homeType"].astype(str)
df["county"] = df["county"].astype(str)
df["event"] = df["event"].astype(str)

In [ ]:
df = df.reset_index(drop=True)

data = [
    (
        row["Unnamed: 0"], row["date"], row["price"], row["pricePerSquareFoot"],
        row["bedrooms"], row["bathrooms"], row["streetAddress"],
        row["city"], row["zipcode"], row["latitude"], row["longitude"],
        row["yearBuilt"], row["livingArea"], row["parking"],
        row["garageSpaces"], row["pool"], row["spa"],
        row["isNewConstruction"], row["hasPetsAllowed"],
        row["homeType"], row["county"], row["event"]
    )
    for _, row in df.iterrows()
]

In [ ]:
engine = create_engine("sqlite:///real_estate.sqlite")

In [10]:
# Connect to SQLite and create real_estate database
conn = sqlite3.connect("real_estate.sqlite")

# Drop real_estate table if it exists
cursor = conn.cursor()
cursor.execute("DROP TABLE IF EXISTS real_estate")

In [11]:
# Create the real_estate table
cursor.execute("""
CREATE TABLE IF NOT EXISTS real_estate (
    id INTEGER PRIMARY KEY,
    date DATETIME,
    price INTEGER,
    pricePerSquareFoot INTEGER,
    bedrooms INTEGER,
    bathrooms REAL,
    streetAddress TEXT,
    city TEXT,
    zipcode TEXT,
    latitude REAL,
    longitude REAL,
    yearBuilt INTEGER,
    livingArea INTEGER,
    parking BOOLEAN,
    garageSpaces INTEGER,
    pool BOOLEAN,
    spa BOOLEAN,
    isNewConstruction BOOLEAN,
    hasPetsAllowed BOOLEAN,
    homeType TEXT,
    county TEXT,
    event TEXT
);
""")

In [12]:
# Query to bulk insert data into the real_estate table
sql = """
INSERT INTO real_estate (
    id, date, price, pricePerSquareFoot, bedrooms, bathrooms, streetAddress, 
    city, zipcode, latitude, longitude, yearBuilt, livingArea, 
    parking, garageSpaces, pool, spa, isNewConstruction, hasPetsAllowed, homeType, county, event
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
"""

In [13]:
# Insert the data into the real_estate table
cursor.executemany(sql, data)
conn.commit()

In [14]:
# Test query to grab first 5 from the database
query = "SELECT * FROM real_estate LIMIT 5"
df_test = pd.read_sql_query(query, conn)

conn.close()

df_test.head()

,id,date,price,pricePerSquareFoot,bedrooms,bathrooms,streetAddress,city,zipcode,latitude,...,livingArea,parking,garageSpaces,pool,spa,isNewConstruction,hasPetsAllowed,homeType,county,event
0,0,2021-01-13,145000,0,0,0.0,0 Moody Ridge Rd,Gold Run,95717.0,39.167866,...,0,0,0,0,0,0,0,LOT,Placer County,Listed for sale
1,1,2021-07-12,675000,404,3,2.0,1476 Belden Ct,Pinole,94564.0,38.001213,...,1671,1,2,0,0,0,0,SINGLE_FAMILY,Contra Costa County,Listed for sale
2,2,2021-07-08,649000,459,3,2.0,3540 Savage Ave,Pinole,94564.0,37.982040,...,1414,1,2,0,0,0,0,SINGLE_FAMILY,Contra Costa County,Listed for sale
3,3,2021-07-07,599000,448,3,2.0,2391 Plum St,Pinole,94564.0,38.004395,...,1336,1,1,0,1,0,0,SINGLE_FAMILY,Contra Costa County,Listed for sale
4,4,2021-07-07,299000,0,0,0.0,2693 Appian Way,Pinole,94564.0,37.986309,...,0,0,0,0,0,0,0,LOT,Contra Costa County,Listed for sale

In [15]:
# TODO: more queries to test the data and glean insights